export type Json = string | number | boolean | null | Json[] | { [key: string]: Json }
export interface Brand { id: number; name: string; slug: string; description: string; enabled: boolean; paused: boolean; config: BrandConfig }
export interface EditorialVoice {description: string; reading_style: string; sentence_length: string; hook_styles: string[]; cta_style: string; banned_phrases: string[]; emoji_policy: 'none'|'sparingly'|'allowed'; hashtag_policy: 'none'|'separate'|'allowed'; humor_level: 'none'|'light'|'playful'; directness: 'gentle'|'balanced'|'direct'; formatting_preferences: string}
export interface BrandConfig { mission: string; tagline?: string; short_bio?: string; voice: string; tone: string; audience: string; editorial?: EditorialVoice; pillars: string[]; prohibited_topics: string[]; terminology: string[]; cta_rules: string; visual: Visual; schedule: {timezone: string; weekdays: number[]; times: string[]; buffer_days: number; window_minutes: number; min_repeat_days: number}; platforms: string[]; permissions: Record<string, string>; interactions: {min_confidence: number; max_replies_hour: number; auto_categories: string[]; blocked_terms: string[]}; moderation_rules: string[]; knowledge_sources: string[]; ai: {provider: string; model: string; temperature: number}; strategy: Record<string, Json>; strategy_locks: string[] }
export interface Visual { background: string; foreground: string; accent: string; muted: string; mark: string; compact_mark?: string; eyebrow?: string; headline_font?: string; body_font?: string; corner_radius?: number; border_treatment?: string; spacing_scale?: number; footer_treatment?: string }
export interface Slide { title: string; body: string; kind: string; items: string[] }
export interface Content { id: number; brand_id: number; topic: string; pillar: string; format: string; hook: string; body: string; slides: Slide[]; caption: string; cta: string; hashtags: string[]; knowledge_refs: number[]; sources: string[]; targets: string[]; parent_id: number | null; status: string; scheduled_at: string | null; published_at: string | null; assets: {key: string; preview: string}[]; quality: {score?: number | null; status?: string; errors?: string[]; warnings?: string[]; editorial?: {score: number; dimensions: Record<string,{score:number;max:number;issues:string[]}>; issues:string[]; note:string}}; revision: number; generation: Record<string, Json> }
export interface Knowledge { id: number; brand_id: number; category: string; title: string; body: string; source: string; verification: string; enabled: boolean; tags: string[]; restrictions: string }
export interface Audit { id: number; action: string; actor: string; actor_type: string; target: string; reason: string; result: string; created_at: string; before: Json; after: Json; details: Json }
export interface Job {id: number; kind: string; target_id: number; status: string; run_at: string; attempts: number; error: string; payload: Json}
export interface Approval {id: number; action: string; target_id: number; status: string; reason: string; created_at: string; payload: Json}
export interface Interaction {id: number; author: string; platform: string; kind: string; body: string; category: string; confidence: number; action: string; draft: string; status: string; taken_over: boolean; created_at: string; reply_id: string}
export interface Overview {brand: Brand; paused: boolean; counts: Record<string, number>; queue: number; approvals: number; community: number; coverage: number; activity: Audit[]; schedule: Content[]}
export interface Account {id: number; platform: string; account_id: string; enabled: boolean; token_configured: boolean; name: string; source: string; permissions: string[]; tasks: string[]; token_status: string; token_type: string; expires_at: number | null; data_access_expires_at: number | null; last_checked: string | null}
export interface Template {id: number; name: string; kind: string; config: Visual; enabled: boolean}
export interface Publication {id: number; content_id: number; platform: string; external_id: string; state: string; attempts: number; error: string; request_state: Json}
export interface Strategy {id: number; before: Json; after: Json; reason: string; status: string}
export interface Analytics {totals: Record<string, number>; groups: Record<string, Record<string, {content: number; saves: number; shares: number; reach: number}>>; top: {id: number; topic: string; platform: string; saves?: number; shares?: number; reach?: number}[]; trend: {date: string; saves?: number; shares?: number; reach?: number}[]; growth: Record<string, {current: number; change: number}>; volume: number; samples: number; note: string}
