import {useState} from 'react'
import {useData} from '../hooks/useData'
import {api,brandPath,label} from '../services/api'
import {Badge,Empty,Field,JsonView,Modal,Panel,Status,useAction} from '../components/ui'
import type {Analytics as Report,Brand,Strategy} from '../types'
export default function Analytics({brand}:{brand:Brand}) {
 const [days,setDays]=useState('30'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[adding,setAdding]=useState(false),[group,setGroup]=useState('pillars'),{busy,run}=useAction()
 const query=days==='custom'&&start&&end?`start=${new Date(start).toISOString()}&end=${new Date(end+'T23:59:59').toISOString()}`:`days=${days==='custom'?'30':days}`
 const {data,error,loading,reload}=useData<Report>(brandPath(brand.id,'/analytics?'+query)),{data:strategy,reload:reloadStrategy}=useData<Strategy[]>(brandPath(brand.id,'/strategy'))
 const max=Math.max(1,...(data?.trend||[]).map(r=>(r.saves||0)+(r.shares||0)))
 return <><div className="toolbar"><div className="segmented">{['7','30','90','custom'].map(d=><button key={d} className={days===d?'selected':''} onClick={()=>setDays(d)}>{d==='custom'?'Custom':d+' days'}</button>)}</div>{days==='custom'&&<><input aria-label="Range start" type="date" value={start} onChange={e=>setStart(e.target.value)}/><input aria-label="Range end" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></>}<div className="grow"/><button onClick={()=>setAdding(true)}>Add metrics</button><button disabled={busy} onClick={()=>run(()=>api(brandPath(brand.id,'/analytics/collect'),'POST'),'Metrics collection queued')}>Sync Meta metrics</button></div><Status error={error} loading={loading}/>{data&&<><div className="stats">{['saves','shares','reach','views'].map(k=><Panel key={k}><small>{label(k)}</small><strong className="stat-value">{data.totals[k]?.toLocaleString()??'—'}</strong><small>Observed lifetime total</small></Panel>)}</div><div className="columns"><Panel title="Useful enough to keep & share"><div className="chart" role="img" aria-label="Save and share snapshots by date">{data.trend.length?data.trend.map(r=><div className="chart-column" key={r.date} title={`${r.date}: ${r.saves||0} saves, ${r.shares||0} shares`}><div className="chart-bars"><div style={{height:`${(r.saves||0)/max*180}px`}}/><div className="shares" style={{height:`${(r.shares||0)/max*180}px`}}/></div><small>{r.date.slice(5)}</small></div>):<Empty title="Your first insights are ahead" text="Connect supported platform metrics or add an observed snapshot. No sample data is shown."/>}</div><div className="legend"><span/>Saves <span/>Shares</div><p className="muted">{data.note}</p></Panel><Panel title="What’s working"><select aria-label="Performance grouping" value={group} onChange={e=>setGroup(e.target.value)}>{['pillars','formats','templates','hours'].map(g=><option key={g} value={g}>{label(g)}</option>)}</select>{Object.entries(data.groups[group]||{}).map(([name,v])=><div key={name} className="list-row"><div className="grow"><strong>{name}</strong><small>{v.content} observed posts · {v.reach} reach</small></div><strong>{v.saves+v.shares}<small>saves + shares</small></strong></div>)}<p className="muted">{data.volume} published items in this range · {data.samples} content/platform samples</p>{Object.entries(data.growth).map(([p,v])=><p key={p}>{label(p)}: {v.current} followers ({v.change>=0?'+':''}{v.change} observed change)</p>)}</Panel></div><Panel title="Top content by saves & shares"><table><thead><tr><th>Content</th><th>Platform</th><th>Saves</th><th>Shares</th><th>Reach</th></tr></thead><tbody>{data.top.map((c,i)=><tr key={i}><td>{c.topic}</td><td>{c.platform}</td><td>{c.saves??'—'}</td><td>{c.shares??'—'}</td><td>{c.reach??'—'}</td></tr>)}</tbody></table></Panel></>}
 <Panel title="Conservative strategy feedback" action={<button disabled={busy} onClick={()=>run(async()=>{await api(brandPath(brand.id,'/strategy'),'POST');await reloadStrategy()},'Strategy recommendation recorded')}>Review performance</button>}><p className="muted">Requires 20 observations and five samples in at least two pillars. Adjustments favor saves and shares, preserve diversity, and respect locks.</p>{strategy?.map(s=><div className="strategy-row" key={s.id}><Badge>{s.status}</Badge><p>{s.reason}</p><details><summary>Compare adjustment</summary><JsonView value={{before:s.before,after:s.after}}/></details>{['PROPOSED','APPLIED'].includes(s.status)&&<button disabled={busy} onClick={()=>run(async()=>{await api(brandPath(brand.id,`/strategy/${s.id}/${s.status==='APPLIED'?'revert':'apply'}`),'POST');await reloadStrategy()},'Strategy updated')}>{s.status==='APPLIED'?'Revert change':'Apply recommendation'}</button>}</div>)}</Panel>
 {adding&&<Modal title="Record observed metrics" close={()=>setAdding(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const metrics=JSON.parse(String(f.get('metrics')));await api(brandPath(brand.id,'/analytics/snapshots'),'POST',{content_id:f.get('content')?Number(f.get('content')):null,platform:f.get('platform'),metrics});setAdding(false);await reload()},'Snapshot recorded')}}><Field label="Content ID (leave blank for account follower metrics)"><input name="content" type="number"/></Field><Field label="Platform"><select name="platform">{['manual','instagram','facebook'].map(p=><option key={p}>{p}</option>)}</select></Field><Field label="Metrics JSON" hint="Supported: reach, impressions, views, likes, comments, shares, saves, followers, follower_change, watch_seconds, retention"><textarea name="metrics" rows={6} required placeholder={'{"saves": 12, "shares": 4}'}/></Field><button className="primary" disabled={busy}>Save snapshot</button></form></Modal>}</>
}
