import {useData} from '../hooks/useData'
import {api,brandPath,date,label} from '../services/api'
import {Badge,Empty,JsonView,Panel,Status,useAction} from '../components/ui'
import type {Approval,Brand,Content,Interaction} from '../types'
export default function Approvals({brand,navigate}:{brand:Brand;navigate:(page:string,id?:number)=>void}) {
 const {data,error,loading,reload}=useData<Approval[]>(brandPath(brand.id,'/approvals')), {data:content}=useData<Content[]>(brandPath(brand.id,'/content')),{data:community}=useData<Interaction[]>(brandPath(brand.id,'/community')),{busy,run}=useAction()
 const pending=data?.filter(a=>a.status==='PENDING')||[]
 return <><div className="info-banner"><p>Review the exact action and target before approving. Editing content invalidates older approvals. Rejected publishing plans are archived for replacement.</p></div><Status error={error} loading={loading}/>{!loading&&!pending.length&&<Empty title="You’re all caught up" text="Actions that need your judgment will wait here. Content drafts can be reviewed in the content library."/>}<div className="approval-list">{pending.map(a=>{const c=['publish','schedule','render'].includes(a.action)?content?.find(c=>c.id===a.target_id):null;const i=['comment_reply','dm_reply','hide','delete'].includes(a.action)?community?.find(i=>i.id===a.target_id):null;return <Panel key={a.id}><div className="panel-heading"><div><small className="eyebrow">{label(a.action)} · REQUEST #{a.id}</small><h3>{c?.topic||i?.body||`Target #${a.target_id}`}</h3><small>{date(a.created_at)}</small></div><Badge>{a.status}</Badge></div>{c&&<><p>{c.caption}</p><button onClick={()=>navigate('Create',c.id)}>Edit & preview content</button></>}{i&&<p>{i.draft}</p>}<JsonView value={a.payload}/><div className="button-row"><button className="primary" disabled={busy} onClick={()=>run(async()=>{await api(brandPath(brand.id,`/approvals/${a.id}`),'POST',{approved:true,reason:'Reviewed by administrator'});await reload()},'Action approved')}>Approve action</button><button disabled={busy} onClick={()=>{const reason=prompt('Reason for rejection');if(reason)void run(async()=>{await api(brandPath(brand.id,`/approvals/${a.id}`),'POST',{approved:false,reason});await reload()},'Request rejected')}}>Reject</button></div></Panel>})}</div><Panel title="Recent decisions">{data?.filter(a=>a.status!=='PENDING').slice(0,15).map(a=><div className="list-row" key={a.id}><div className="grow"><strong>{label(a.action)} · #{a.target_id}</strong><small>{a.reason}</small></div><Badge>{a.status}</Badge></div>)}</Panel></>
}
