import {useState} from 'react'
import {ChevronLeft,ChevronRight,Plus} from 'lucide-react'
import {useData} from '../hooks/useData'
import {brandPath,date} from '../services/api'
import {Badge,Panel,Status} from '../components/ui'
import type {Brand,Content} from '../types'
export default function Calendar({brand,navigate}:{brand:Brand;navigate:(page:string,id?:number)=>void}) {
 const {data,error,loading}=useData<Content[]>(brandPath(brand.id,'/content')), [anchor,setAnchor]=useState(new Date()),[mode,setMode]=useState('Week')
 const start=new Date(anchor);if(mode==='Week')start.setDate(start.getDate()-(start.getDay()+6)%7);start.setHours(0,0,0,0)
 const days=Array.from({length:mode==='Week'?7:1},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d})
 return <><div className="toolbar"><button aria-label="Previous period" onClick={()=>setAnchor(new Date(anchor.getTime()-(mode==='Week'?7:1)*86400000))}><ChevronLeft size={18}/></button><h2>{start.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button aria-label="Next period" onClick={()=>setAnchor(new Date(anchor.getTime()+(mode==='Week'?7:1)*86400000))}><ChevronRight size={18}/></button><button onClick={()=>setAnchor(new Date())}>Today</button><div className="grow"/><div className="segmented">{['Week','Day'].map(m=><button key={m} className={mode===m?'selected':''} onClick={()=>setMode(m)}>{m}</button>)}</div><button className="primary" onClick={()=>navigate('Create')}><Plus size={16}/>Create</button></div><p className="muted">Calendar shown in your device timezone. Brand schedule: {brand.config.schedule.timezone} · {brand.config.schedule.times.join(', ')}.</p><Status error={error} loading={loading}/><div className={'calendar '+(mode==='Day'?'day':'')}>{days.map(d=><div key={d.toISOString()} className="calendar-day"><header><span>{d.toLocaleDateString(undefined,{weekday:'short'})}</span><strong className={d.toDateString()===new Date().toDateString()?'today':''}>{d.getDate()}</strong></header>{(data||[]).filter(c=>c.scheduled_at&&new Date(c.scheduled_at+'Z').toDateString()===d.toDateString()).map(c=><button className="calendar-item" key={c.id} onClick={()=>navigate('Create',c.id)}><small>{date(c.scheduled_at)}</small><strong>{c.topic}</strong><span>{c.pillar}</span><Badge>{c.status}</Badge></button>)}</div>)}</div><Panel title="Ready for a date"><div className="ready-list">{(data||[]).filter(c=>c.status==='APPROVED').map(c=><button key={c.id} onClick={()=>navigate('Create',c.id)}><strong>{c.topic}</strong><small>{c.pillar}</small><Badge>APPROVED</Badge></button>)}{!data?.some(c=>c.status==='APPROVED')&&<p className="muted">Approved content will appear here, ready to schedule.</p>}</div></Panel></>
}
