import {useEffect,useState} from 'react'
import {Plus, Trash2, Sparkles, Paintbrush, Save, Download} from 'lucide-react'
import {api,brandPath,formats,kinds,label} from '../services/api'
import {readableError} from '../services/validation'
import {eligibleCandidates} from '../services/knowledgeCandidates'
import {Badge,Field,Panel,useAction,Status} from '../components/ui'
import type {Brand,Content,Knowledge,Slide} from '../types'

type Draft=Pick<Content,'topic'|'pillar'|'format'|'hook'|'body'|'slides'|'caption'|'cta'|'hashtags'|'knowledge_refs'|'sources'|'targets'|'parent_id'>
const fresh=(brand:Brand):Draft=>({topic:'',pillar:brand.config.pillars[0]||'General',format:'carousel',hook:'',body:'',slides:[{title:'',body:'',kind:'cover',items:[]}],caption:'',cta:'',hashtags:[],knowledge_refs:[],sources:[],targets:brand.config.platforms,parent_id:null})
const normalized=(value:string)=>value.normalize('NFKC').replace(/\s+/g,' ').trim().toLocaleLowerCase()
export default function Editor({brand,id,navigate}: {brand:Brand;id?:number;navigate:(page:string,id?:number)=>void}) {
 const [draft,setDraft]=useState<Draft>(fresh(brand)),[item,setItem]=useState<Content|null>(null),[candidates,setCandidates]=useState<{key:string;items:Knowledge[];loading:boolean;error:string}>({key:'',items:[],loading:false,error:''}),[when,setWhen]=useState(''),[override,setOverride]=useState(false),[reason,setReason]=useState(''),[tab,setTab]=useState('Write'),[error,setError]=useState('')
 const {busy,run}=useAction(),path=(suffix:string)=>brandPath(brand.id,suffix)
 const candidateKey=JSON.stringify([brand.id,draft.topic,draft.pillar])
 const knowledge=candidates.key===candidateKey?eligibleCandidates(candidates.items,brand.id,draft.pillar):[]
 useEffect(()=>{let active=true;if(id)api<Content>(path(`/content/${id}`)).then(c=>{if(active){setItem(c);setDraft({...Object.fromEntries(Object.keys(fresh(brand)).map(k=>[k,c[k as keyof Content]])),slides:c.slides.length?c.slides:fresh(brand).slides} as Draft)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[id,brand.id])
 useEffect(()=>{let active=true;setCandidates({key:candidateKey,items:[],loading:!!draft.topic.trim()&&!!draft.pillar.trim(),error:''})
  if(!draft.topic.trim()||!draft.pillar.trim())return()=>{active=false}
  const timer=setTimeout(()=>{const query=new URLSearchParams({topic:draft.topic,pillar:draft.pillar})
   api<Knowledge[]>(path('/knowledge/candidates?'+query.toString())).then(items=>{if(active)setCandidates({key:candidateKey,items:eligibleCandidates(items,brand.id,draft.pillar),loading:false,error:''})})
    .catch(reason=>{if(active)setCandidates({key:candidateKey,items:[],loading:false,error:readableError(reason)})})},250)
  return()=>{active=false;clearTimeout(timer)}},[candidateKey])
 function field<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(d=>({...d,[key]:value,...(key==='topic'||key==='pillar'?{knowledge_refs:[]}:{} )}))}
 function slide(index:number,patch:Partial<Slide>){field('slides',draft.slides.map((s,i)=>i===index?{...s,...patch}:s))}
 async function save(){setError('');try{const slides=draft.slides.filter((slide,index)=>!(index===0&&slide.kind==='cover'&&!slide.title.trim()&&!slide.body.trim()&&slide.items.every(value=>!value.trim())))
  const result=await api<Content>(path(id?`/content/${id}`:'/content'),id?'PUT':'POST',{...draft,slides});setItem(result);if(!id)navigate('Create',result.id);return result
 }catch(reason){const message=`Draft couldn't be saved: ${readableError(reason)}`;setError(message);throw new Error(message)}}
 async function generate(){setError('');try{
  if(!brand.enabled)throw new Error('Enable this brand before generating')
  if(draft.topic.trim().length<3)throw new Error('Enter a topic of at least 3 characters')
  if(!brand.config.pillars.some(pillar=>normalized(pillar)===normalized(draft.pillar)))throw new Error('Choose a configured pillar for this brand')
  const query=new URLSearchParams({topic:draft.topic,pillar:draft.pillar})
  const current=await api<Knowledge[]>(path('/knowledge/candidates?'+query.toString()))
  const eligible=eligibleCandidates(current,brand.id,draft.pillar)
  if(!eligible.length)throw new Error('Approve and enable knowledge for this pillar before generating')
  if(!draft.knowledge_refs.length)throw new Error('Select and attach approved knowledge before generating')
  if(draft.knowledge_refs.some(ref=>!eligible.some(item=>item.id===ref)))throw new Error('Knowledge selection changed. Review the current candidates before generating')
  await api(path('/generate'),'POST',{topic:draft.topic,pillar:draft.pillar,format:draft.format,parent_id:item?.id||draft.parent_id,knowledge_refs:draft.knowledge_refs});navigate('System')
 }catch(reason){const message=readableError(reason);setError(message);throw new Error(message)}}
 async function action(name:string,body?:unknown){if(!id)throw new Error('Save your draft first');const result=await api<Content>(path(`/content/${id}/${name}`),'POST',body);if(result.topic)setItem(result)}
 return <><div className="toolbar"><div className="grow"><Badge>{item?.status||'NEW DRAFT'}</Badge>{item&&<span className="muted"> Revision {item.revision} · {item.status==='DRAFT'||item.quality.score==null?'Not scored yet':`Quality ${item.quality.score}/100`}</span>}</div><button disabled={busy} onClick={()=>run(save)}><Save size={16}/>Save draft</button><button className="primary" disabled={busy||!draft.topic} onClick={()=>run(generate,'Generation queued')}><Sparkles size={16}/>{id?'Generate variant':'Generate with local AI'}</button></div><Status error={error}/>
 <div className="editor-grid"><div><Panel title="The idea"><div className="form-grid"><Field label="Topic"><input value={draft.topic} onChange={e=>field('topic',e.target.value)} placeholder="One useful thing your audience should know"/></Field><Field label="Pillar"><input list="pillars" value={draft.pillar} onChange={e=>field('pillar',e.target.value)}/><datalist id="pillars">{brand.config.pillars.map(p=><option key={p}>{p}</option>)}</datalist></Field><Field label="Format"><select value={draft.format} onChange={e=>field('format',e.target.value)}>{formats.map(f=><option key={f} value={f}>{label(f)}</option>)}</select></Field><Field label="Hook"><textarea rows={2} value={draft.hook} onChange={e=>field('hook',e.target.value)}/></Field></div></Panel>
 <Panel title="Make it useful" action={<div className="segmented">{['Write','Preview'].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>}>
 {tab==='Write'?<><Field label="Body / script"><textarea rows={4} value={draft.body} onChange={e=>field('body',e.target.value)}/></Field>{draft.slides.map((s,i)=><div className="slide-editor" key={i}><div className="panel-heading"><strong>Slide {String(i+1).padStart(2,'0')}</strong><button className="icon-button" aria-label={`Remove slide ${i+1}`} onClick={()=>field('slides',draft.slides.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div><div className="form-grid"><Field label="Layout"><select value={s.kind} onChange={e=>slide(i,{kind:e.target.value})}>{kinds.map(k=><option key={k} value={k}>{label(k)}</option>)}</select></Field><Field label="Title"><input value={s.title} onChange={e=>slide(i,{title:e.target.value})}/></Field></div><Field label="Explanation"><textarea rows={3} value={s.body} onChange={e=>slide(i,{body:e.target.value})}/></Field><Field label="List items / column content" hint="One item per line. Two-column layouts need at least two items."><textarea value={s.items.join('\n')} onChange={e=>slide(i,{items:e.target.value.split('\n')})}/></Field><div className="button-row"><button disabled={i===0} onClick={()=>{const slides=[...draft.slides];[slides[i-1],slides[i]]=[slides[i],slides[i-1]];field('slides',slides)}}>Move up</button><button disabled={i===draft.slides.length-1} onClick={()=>{const slides=[...draft.slides];[slides[i+1],slides[i]]=[slides[i],slides[i+1]];field('slides',slides)}}>Move down</button></div></div>)}<button onClick={()=>field('slides',[...draft.slides,{title:'',body:'',kind:'statement',items:[]}])}><Plus size={16}/>Add slide</button></>:<div className="preview-grid">{item?.assets.length?item.assets.map((a,i)=><a key={a.key} href={'/api/media/'+a.key} target="_blank" rel="noreferrer"><img src={'/api/media/'+a.key} alt={`Rendered slide ${i+1}`}/></a>):<p>Save, then render your graphics to see a faithful preview.</p>}</div>}
 </Panel><Panel title="Caption & context"><Field label="Caption"><textarea rows={5} value={draft.caption} onChange={e=>field('caption',e.target.value)}/></Field><Field label="Call to action"><input value={draft.cta} onChange={e=>field('cta',e.target.value)}/></Field><Field label="Hashtags (space separated)"><input value={draft.hashtags.join(' ')} onChange={e=>field('hashtags',e.target.value.split(/\s+/).filter(Boolean))}/></Field><Field label="Source references (one per line)"><textarea value={draft.sources.join('\n')} onChange={e=>field('sources',e.target.value.split('\n').filter(Boolean))}/></Field></Panel></div>
 <aside><Panel title="Publishing checklist"><div className="stack"><button disabled={busy||!id} onClick={()=>run(async()=>{await save();await action('render');setTab('Preview')},'Graphics rendered')}><Paintbrush size={16}/>Save & render graphics</button>{item?.status==='DRAFT'&&<button disabled={busy} onClick={()=>run(()=>action('transition',{state:'REVIEW'}),'Sent to review')}>Send to review</button>}{item?.status==='REVIEW'&&<button disabled={busy} className="primary" onClick={()=>run(()=>action('transition',{state:'APPROVED'}),'Content approved')}>Approve content</button>}{item&&['APPROVED','SCHEDULED','FAILED'].includes(item.status)&&<button disabled={busy} onClick={()=>run(()=>action('transition',{state:item.status==='SCHEDULED'?'APPROVED':'DRAFT'}),'Returned for editing')}>{item.status==='SCHEDULED'?'Unschedule':'Return to draft'}</button>}<button disabled={busy||!id||!['APPROVED','SCHEDULED','PUBLISHED'].includes(item?.status||'')} onClick={()=>run(async()=>{const r=await api<{url:string}>(path(`/content/${id}/export`),'POST');window.location.assign(r.url)},'Export prepared')}><Download size={16}/>Manual export</button></div>{item?.quality.warnings?.map(w=><p className="notice" key={w}>{w}</p>)}{item?.quality.errors?.map(w=><p className="error" key={w}>{w}</p>)}</Panel>
 <Panel title="Grounded in knowledge"><p className="muted">Current topic and pillar: {draft.pillar}. Candidates refresh as you edit; Generate checks them again.</p>{candidates.key===candidateKey&&candidates.loading&&<p className="muted">Finding eligible knowledge…</p>}{candidates.key===candidateKey&&candidates.error&&<p role="alert" className="error">{candidates.error}</p>}<div className="check-list">{knowledge.map(k=><label key={k.id}><input type="checkbox" checked={draft.knowledge_refs.includes(k.id)} onChange={e=>field('knowledge_refs',e.target.checked?[...draft.knowledge_refs,k.id]:draft.knowledge_refs.filter(x=>x!==k.id))}/>{k.title}</label>)}</div>{!!knowledge.length&&<p className="muted">{draft.knowledge_refs.length} selected · {item?.knowledge_refs.length||0} attached to saved draft</p>}{draft.knowledge_refs.length>0&&<button disabled={busy} onClick={()=>run(save,'Knowledge attached to draft')}><Save size={16}/>Save selected knowledge</button>}{candidates.key===candidateKey&&!candidates.loading&&draft.knowledge_refs.some(ref=>!knowledge.some(k=>k.id===ref))&&<p className="notice">Some saved references are no longer current candidates. Review them before generating.</p>}{candidates.key===candidateKey&&!candidates.loading&&!knowledge.length&&<p className="muted">No approved, retrieval-enabled knowledge matches this pillar. Approve relevant knowledge before generating.</p>}{!draft.knowledge_refs.length&&!!knowledge.length&&<p className="notice">Select approved knowledge to ground generation. Nothing is attached yet.</p>}</Panel>
 <Panel title="Where & when"><div className="check-list">{['manual','instagram','facebook'].map(p=><label key={p}><input type="checkbox" checked={draft.targets.includes(p)} onChange={e=>field('targets',e.target.checked?[...draft.targets,p]:draft.targets.filter(x=>x!==p))}/>{label(p)}</label>)}</div><p className="muted">Save target changes before approval.</p><Field label="Publish time (your device timezone)"><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></Field><label className="check"><input type="checkbox" checked={override} onChange={e=>setOverride(e.target.checked)}/>Override brand posting window</label>{override&&<Field label="Override reason"><input value={reason} onChange={e=>setReason(e.target.value)}/></Field>}<button disabled={busy||!when||!id} onClick={()=>run(async()=>{await action('schedule',{run_at:new Date(when).toISOString(),override_window:override,reason});navigate('Calendar')},'Content scheduled')}>Schedule content</button><button className="primary full" disabled={busy||!id||!['APPROVED','SCHEDULED','FAILED'].includes(item?.status||'')} onClick={()=>{if(window.confirm('Publish this approved content to its configured targets now?'))void run(()=>action('publish'),'Publish request processed')}}>Publish now</button></Panel>
 {item&&<Panel title="Version & provenance"><p>Parent: {item.parent_id?`#${item.parent_id}`:'Original content'}</p><details><summary>Generation metadata</summary><pre className="json-view">{JSON.stringify(item.generation,null,2)}</pre></details><button onClick={()=>run(()=>action('transition',{state:'ARCHIVED',reason:'Archived by administrator'}),'Content archived')} disabled={busy||item.status==='ARCHIVED'||item.status==='PUBLISHING'}>Archive content</button></Panel>}</aside></div></>
}
