import {useEffect,useState} from 'react'
import {Plus, Trash2, Sparkles, Paintbrush, Save, Download} from 'lucide-react'
import {api,brandPath,formats,kinds,label} from '../services/api'
import {Badge,Field,Panel,useAction,Status} from '../components/ui'
import type {Brand,Content,Knowledge,Slide} from '../types'

type Draft=Pick<Content,'topic'|'pillar'|'format'|'hook'|'body'|'slides'|'caption'|'cta'|'hashtags'|'knowledge_refs'|'sources'|'targets'|'parent_id'>
const fresh=(brand:Brand):Draft=>({topic:'',pillar:brand.config.pillars[0]||'General',format:'carousel',hook:'',body:'',slides:[{title:'',body:'',kind:'cover',items:[]}],caption:'',cta:'',hashtags:[],knowledge_refs:[],sources:[],targets:brand.config.platforms,parent_id:null})
export default function Editor({brand,id,navigate}: {brand:Brand;id?:number;navigate:(page:string,id?:number)=>void}) {
 const [draft,setDraft]=useState<Draft>(fresh(brand)),[item,setItem]=useState<Content|null>(null),[knowledge,setKnowledge]=useState<Knowledge[]>([]),[when,setWhen]=useState(''),[override,setOverride]=useState(false),[reason,setReason]=useState(''),[tab,setTab]=useState('Write'),[error,setError]=useState('')
 const {busy,run}=useAction(),path=(suffix:string)=>brandPath(brand.id,suffix)
 useEffect(()=>{api<Knowledge[]>(path('/knowledge')).then(setKnowledge).catch(e=>setError(e.message));if(id)api<Content>(path(`/content/${id}`)).then(c=>{setItem(c);setDraft(Object.fromEntries(Object.keys(fresh(brand)).map(k=>[k,c[k as keyof Content]])) as Draft)}).catch(e=>setError(e.message))},[id,brand.id])
 function field<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(d=>({...d,[key]:value}))}
 function slide(index:number,patch:Partial<Slide>){field('slides',draft.slides.map((s,i)=>i===index?{...s,...patch}:s))}
 async function save(){const result=await api<Content>(path(id?`/content/${id}`:'/content'),id?'PUT':'POST',draft);setItem(result);if(!id)navigate('Create',result.id);return result}
 async function action(name:string,body?:unknown){if(!id)throw new Error('Save your draft first');const result=await api<Content>(path(`/content/${id}/${name}`),'POST',body);if(result.topic)setItem(result)}
 return <><div className="toolbar"><div className="grow"><Badge>{item?.status||'NEW DRAFT'}</Badge>{item&&<span className="muted"> Revision {item.revision} · Quality {item.quality.score??'—'}/100</span>}</div><button disabled={busy} onClick={()=>run(save)}><Save size={16}/>Save draft</button><button className="primary" disabled={busy||!draft.topic} onClick={()=>run(async()=>{await api(path('/generate'),'POST',{topic:draft.topic,pillar:draft.pillar,format:draft.format,parent_id:item?.id||draft.parent_id});navigate('System')},'Generation queued')}><Sparkles size={16}/>{id?'Generate variant':'Generate with local AI'}</button></div><Status error={error}/>
 <div className="editor-grid"><div><Panel title="The idea"><div className="form-grid"><Field label="Topic"><input value={draft.topic} onChange={e=>field('topic',e.target.value)} placeholder="One useful thing your audience should know"/></Field><Field label="Pillar"><input list="pillars" value={draft.pillar} onChange={e=>field('pillar',e.target.value)}/><datalist id="pillars">{brand.config.pillars.map(p=><option key={p}>{p}</option>)}</datalist></Field><Field label="Format"><select value={draft.format} onChange={e=>field('format',e.target.value)}>{formats.map(f=><option key={f} value={f}>{label(f)}</option>)}</select></Field><Field label="Hook"><textarea rows={2} value={draft.hook} onChange={e=>field('hook',e.target.value)}/></Field></div></Panel>
 <Panel title="Make it useful" action={<div className="segmented">{['Write','Preview'].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>}>
 {tab==='Write'?<><Field label="Body / script"><textarea rows={4} value={draft.body} onChange={e=>field('body',e.target.value)}/></Field>{draft.slides.map((s,i)=><div className="slide-editor" key={i}><div className="panel-heading"><strong>Slide {String(i+1).padStart(2,'0')}</strong><button className="icon-button" aria-label={`Remove slide ${i+1}`} onClick={()=>field('slides',draft.slides.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div><div className="form-grid"><Field label="Layout"><select value={s.kind} onChange={e=>slide(i,{kind:e.target.value})}>{kinds.map(k=><option key={k} value={k}>{label(k)}</option>)}</select></Field><Field label="Title"><input value={s.title} onChange={e=>slide(i,{title:e.target.value})}/></Field></div><Field label="Explanation"><textarea rows={3} value={s.body} onChange={e=>slide(i,{body:e.target.value})}/></Field><Field label="List items / column content" hint="One item per line. Two-column layouts need at least two items."><textarea value={s.items.join('\n')} onChange={e=>slide(i,{items:e.target.value.split('\n')})}/></Field><div className="button-row"><button disabled={i===0} onClick={()=>{const slides=[...draft.slides];[slides[i-1],slides[i]]=[slides[i],slides[i-1]];field('slides',slides)}}>Move up</button><button disabled={i===draft.slides.length-1} onClick={()=>{const slides=[...draft.slides];[slides[i+1],slides[i]]=[slides[i],slides[i+1]];field('slides',slides)}}>Move down</button></div></div>)}<button onClick={()=>field('slides',[...draft.slides,{title:'',body:'',kind:'statement',items:[]}])}><Plus size={16}/>Add slide</button></>:<div className="preview-grid">{item?.assets.length?item.assets.map((a,i)=><a key={a.key} href={'/api/media/'+a.key} target="_blank" rel="noreferrer"><img src={'/api/media/'+a.key} alt={`Rendered slide ${i+1}`}/></a>):<p>Save, then render your graphics to see a faithful preview.</p>}</div>}
 </Panel><Panel title="Caption & context"><Field label="Caption"><textarea rows={5} value={draft.caption} onChange={e=>field('caption',e.target.value)}/></Field><Field label="Call to action"><input value={draft.cta} onChange={e=>field('cta',e.target.value)}/></Field><Field label="Hashtags (space separated)"><input value={draft.hashtags.join(' ')} onChange={e=>field('hashtags',e.target.value.split(/\s+/).filter(Boolean))}/></Field><Field label="Source references (one per line)"><textarea value={draft.sources.join('\n')} onChange={e=>field('sources',e.target.value.split('\n').filter(Boolean))}/></Field></Panel></div>
 <aside><Panel title="Publishing checklist"><div className="stack"><button disabled={busy||!id} onClick={()=>run(async()=>{await save();await action('render');setTab('Preview')},'Graphics rendered')}><Paintbrush size={16}/>Save & render graphics</button>{item?.status==='DRAFT'&&<button disabled={busy} onClick={()=>run(()=>action('transition',{state:'REVIEW'}),'Sent to review')}>Send to review</button>}{item?.status==='REVIEW'&&<button disabled={busy} className="primary" onClick={()=>run(()=>action('transition',{state:'APPROVED'}),'Content approved')}>Approve content</button>}{item&&['APPROVED','SCHEDULED','FAILED'].includes(item.status)&&<button disabled={busy} onClick={()=>run(()=>action('transition',{state:item.status==='SCHEDULED'?'APPROVED':'DRAFT'}),'Returned for editing')}>{item.status==='SCHEDULED'?'Unschedule':'Return to draft'}</button>}<button disabled={busy||!id} onClick={()=>run(async()=>{const r=await api<{url:string}>(path(`/content/${id}/export`),'POST');window.location.assign(r.url)},'Export prepared')}><Download size={16}/>Manual export</button></div>{item?.quality.warnings?.map(w=><p className="notice" key={w}>{w}</p>)}{item?.quality.errors?.map(w=><p className="error" key={w}>{w}</p>)}</Panel>
 <Panel title="Grounded in knowledge"><div className="check-list">{knowledge.filter(k=>k.enabled&&k.verification==='APPROVED').map(k=><label key={k.id}><input type="checkbox" checked={draft.knowledge_refs.includes(k.id)} onChange={e=>field('knowledge_refs',e.target.checked?[...draft.knowledge_refs,k.id]:draft.knowledge_refs.filter(x=>x!==k.id))}/>{k.title}</label>)}</div>{!knowledge.some(k=>k.verification==='APPROVED')&&<p className="muted">Add and approve knowledge before generating factual content.</p>}</Panel>
 <Panel title="Where & when"><div className="check-list">{['manual','instagram','facebook'].map(p=><label key={p}><input type="checkbox" checked={draft.targets.includes(p)} onChange={e=>field('targets',e.target.checked?[...draft.targets,p]:draft.targets.filter(x=>x!==p))}/>{label(p)}</label>)}</div><p className="muted">Save target changes before approval.</p><Field label="Publish time (your device timezone)"><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></Field><label className="check"><input type="checkbox" checked={override} onChange={e=>setOverride(e.target.checked)}/>Override brand posting window</label>{override&&<Field label="Override reason"><input value={reason} onChange={e=>setReason(e.target.value)}/></Field>}<button disabled={busy||!when||!id} onClick={()=>run(async()=>{await action('schedule',{run_at:new Date(when).toISOString(),override_window:override,reason});navigate('Calendar')},'Content scheduled')}>Schedule content</button><button className="primary full" disabled={busy||!id||!['APPROVED','SCHEDULED','FAILED'].includes(item?.status||'')} onClick={()=>{if(window.confirm('Publish this approved content to its configured targets now?'))void run(()=>action('publish'),'Publish request processed')}}>Publish now</button></Panel>
 {item&&<Panel title="Version & provenance"><p>Parent: {item.parent_id?`#${item.parent_id}`:'Original content'}</p><details><summary>Generation metadata</summary><pre className="json-view">{JSON.stringify(item.generation,null,2)}</pre></details><button onClick={()=>run(()=>action('transition',{state:'ARCHIVED',reason:'Archived by administrator'}),'Content archived')} disabled={busy||item.status==='ARCHIVED'||item.status==='PUBLISHING'}>Archive content</button></Panel>}</aside></div></>
}
