import {useState} from 'react'
import {Plus,Search,BookOpen} from 'lucide-react'
import {useData} from '../hooks/useData'
import {api,brandPath} from '../services/api'
import {Badge,Empty,Field,Modal,Panel,Status,useAction} from '../components/ui'
import type {Brand,Knowledge as Entry} from '../types'
const blank={category:'',title:'',body:'',source:'',verification:'PENDING',enabled:true,tags:[] as string[],restrictions:''}
export default function Knowledge({brand}:{brand:Brand}) {
 const [q,setQ]=useState(''),{data,error,loading,reload}=useData<Entry[]>(brandPath(brand.id,'/knowledge?q='+encodeURIComponent(q))),[editing,setEditing]=useState<(typeof blank & {id?:number})|null>(null),{busy,run}=useAction()
 const update=(key:string,value:unknown)=>setEditing(e=>e?{...e,[key]:value}:e)
 return <><div className="toolbar"><div className="search"><Search size={18}/><input aria-label="Search knowledge" placeholder="Search your trusted knowledge…" value={q} onChange={e=>setQ(e.target.value)}/></div><button className="primary" onClick={()=>setEditing({...blank,category:brand.config.pillars[0]||'General'})}><Plus size={16}/>Add knowledge</button></div><div className="info-banner"><BookOpen size={20}/><p>Your source of truth. Only approved, enabled entries inform AI generation. Keep sources and usage restrictions attached.</p></div><Status error={error} loading={loading}/><div className="knowledge-grid">{data?.map(k=><Panel key={k.id}><div className="panel-heading"><Badge>{k.verification}</Badge><small>{k.enabled?'Enabled':'Disabled'}</small></div><small className="eyebrow">{k.category}</small><h3>{k.title}</h3><p className="clamp">{k.body}</p><div className="tag-row">{k.tags.map(t=><span key={t}>{t}</span>)}</div><button onClick={()=>setEditing(k)}>Review & edit</button></Panel>)}</div>{!loading&&!data?.length&&<Empty title="Build your brand’s source of truth" text="Add practical guidance, a source, and any restrictions. Review it before making it available to your local AI."/>}
 {editing&&<Modal title={editing.id?'Edit knowledge':'Add knowledge'} close={()=>setEditing(null)}><form onSubmit={e=>{e.preventDefault();void run(async()=>{const payload=Object.fromEntries(Object.keys(blank).map(k=>[k,editing[k as keyof typeof editing]]));await api(brandPath(brand.id,editing.id?`/knowledge/${editing.id}`:'/knowledge'),editing.id?'PUT':'POST',payload);setEditing(null);await reload()},'Knowledge saved')}}><Field label="Title"><input required value={editing.title} onChange={e=>update('title',e.target.value)}/></Field><Field label="Category / pillar"><input required value={editing.category} onChange={e=>update('category',e.target.value)}/></Field><Field label="Knowledge body"><textarea required rows={8} value={editing.body} onChange={e=>update('body',e.target.value)}/></Field><Field label="Source / reference"><input value={editing.source} onChange={e=>update('source',e.target.value)}/></Field><Field label="Usage restrictions"><textarea value={editing.restrictions} onChange={e=>update('restrictions',e.target.value)}/></Field><Field label="Tags (comma separated)"><input value={editing.tags.join(', ')} onChange={e=>update('tags',e.target.value.split(',').map(t=>t.trim()))}/></Field><Field label="Verification"><select value={editing.verification} onChange={e=>update('verification',e.target.value)}>{['PENDING','APPROVED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select></Field><label className="check"><input type="checkbox" checked={editing.enabled} onChange={e=>update('enabled',e.target.checked)}/>Available for retrieval</label><button className="primary" disabled={busy}>Save knowledge</button></form></Modal>}</>
}
