import {api,brandPath,label} from '../services/api'
import {Field,Panel,useAction} from '../components/ui'
import {useData} from '../hooks/useData'
import type {Account} from '../types'

export default function MetaAccounts({brandId}:{brandId:number}) {
 const {busy,run}=useAction(), {data:accounts,reload}=useData<Account[]>(brandPath(brandId,'/accounts'))
 async function connect(){const result=await api<{authorization_url:string}>(brandPath(brandId,'/meta/connect'),'POST');window.location.assign(result.authorization_url)}
 return <div className="columns"><Panel title="Meta accounts"><button className="primary" disabled={busy} onClick={()=>run(connect,'Opening Meta authorization')}>Connect Meta</button><p className="muted">Connects managed Pages and linked Instagram professional accounts to this brand. Requires a configured Meta app and HTTPS callback.</p>{accounts?.map(a=><div className="account-row" key={a.id}><h3>{a.name||label(a.platform)} · {label(a.platform)}</h3><p>Account {a.account_id} · {a.source==='oauth'?'Meta connection':'Manual credential'} · {a.enabled?'Selected':'Inactive'}</p><p>Permissions: {a.permissions?.join(', ')||'Not inspected'}</p><p>Token: {label(a.token_status)} · Expires: {a.expires_at?new Date(a.expires_at*1000).toLocaleString():'No expiry reported'} · Last checked: {a.last_checked?new Date(a.last_checked).toLocaleString():'Never'}</p><p>Token type: {a.token_type||'Unknown'} · Data access expires: {a.data_access_expires_at?new Date(a.data_access_expires_at*1000).toLocaleString():'Not reported'}</p><div className="button-row">{!a.enabled&&<button disabled={busy} onClick={()=>run(async()=>{await api(brandPath(brandId,`/accounts/${a.id}/activate`),'POST');await reload()},'Publishing account selected')}>Use for publishing</button>}<button disabled={busy} onClick={()=>run(async()=>{await api(brandPath(brandId,`/accounts/${a.id}/check`),'POST');await reload()},'Connection checked')}>Check connection</button><button disabled={busy} onClick={()=>run(connect,'Opening Meta authorization')}>Reconnect</button><button disabled={busy} onClick={()=>{if(confirm('Remove this account’s locally stored credential?'))void run(async()=>{await api(brandPath(brandId,`/accounts/${a.id}`),'DELETE');await reload()},'Local credential removed')}}>Disconnect</button></div></div>)}{!accounts?.length&&<p className="muted">No Meta accounts connected. Manual export remains available.</p>}</Panel><Panel title="Advanced · manual credential"><form onSubmit={e=>{e.preventDefault();const element=e.currentTarget,f=new FormData(element);void run(async()=>{await api(brandPath(brandId,'/accounts'),'POST',{platform:f.get('platform'),account_id:f.get('account_id'),token:f.get('token'),enabled:true});element.reset();await reload()},'Credential encrypted and stored')}}><Field label="Platform"><select name="platform"><option value="instagram">Instagram professional account</option><option value="facebook">Facebook Page</option></select></Field><Field label="Account / Page ID"><input name="account_id" required autoComplete="off"/></Field><Field label="Authorized access token"><input name="token" type="password" required autoComplete="new-password"/></Field><button className="primary" disabled={busy}>Save encrypted token</button></form><p className="muted">Use this when Meta Login is unavailable. The complete token is never shown again.</p></Panel></div>
}
