import {useState} from 'react'
import {Download, Pause, Play, RefreshCw, RotateCcw, ShieldAlert} from 'lucide-react'
import {useData} from '../hooks/useData'
import {api, apiUrl, brandPath, date, label} from '../services/api'
import {Badge, Empty, Field, JsonView, Panel, Status, useAction} from '../components/ui'
import type {Audit, Brand, Content, Job, Publication} from '../types'

type Health = Record<string, string | number | boolean | Record<string, unknown>>
type BackupFile = {name: string; size: number; created_at: number}

export default function Operations({brand, page, refresh}: {brand: Brand; page: string; refresh: () => void}) {
  const {busy, run} = useAction()
  const {data: health, error: healthError, loading: healthLoading, reload: reloadHealth} = useData<Health>(`/system?brand_id=${brand.id}`)
  const {data: jobs, error: jobsError, loading: jobsLoading, reload: reloadJobs} = useData<Job[]>(brandPath(brand.id, '/jobs'))
  const {data: publications, error: publicationsError, loading: publicationsLoading, reload: reloadPublications} = useData<Publication[]>(brandPath(brand.id, '/publications'))
  const {data: content} = useData<Content[]>(brandPath(brand.id, '/content'))
  const {data: activity, error: activityError, loading: activityLoading, reload: reloadActivity} = useData<Audit[]>(brandPath(brand.id, '/activity'))
  const {data: backups, error: backupsError, loading: backupsLoading, reload: reloadBackups} = useData<BackupFile[]>('/backups')
  const [editing, setEditing] = useState<number | null>(null)
  const [externalId, setExternalId] = useState(''), [reason, setReason] = useState(''), [absent, setAbsent] = useState(false)

  if (page === 'System') return <>
    <div className="toolbar"><p className="muted grow">Local service health and automation controls.</p><button disabled={busy} onClick={() => run(reloadHealth, 'System status refreshed')}><RefreshCw size={16}/>Refresh checks</button></div>
    <Status error={healthError} loading={healthLoading}/>{health&&<>
      <div className="health-grid">{Object.entries(health).filter(([key])=>!['ai','global_paused','brand_paused','brand_enabled','meta_api_version','free_gb'].includes(key)).map(([key,value])=><Panel key={key}><small>{label(key)}</small><strong className="health-value">{typeof value==='object'?JSON.stringify(value):String(value)}</strong></Panel>)}</div>
      <div className="columns"><Panel title="Outward action controls"><p className="muted">Controls scheduled and automatic outward actions across all brands. Owner-confirmed manual publishing remains available when the selected brand is active.</p><div className="permission-row"><div><strong>Global autonomous actions</strong><small>Scheduled and automatic outward actions</small></div><Badge>{health.global_paused?'PAUSED':'ACTIVE'}</Badge><button disabled={busy} onClick={()=>run(async()=>{await api('/pause','POST',{paused:!health.global_paused});await reloadHealth();refresh()},health.global_paused?'Global autonomous actions resumed':'Global autonomous actions paused')}>{health.global_paused?<Play size={16}/>:<Pause size={16}/>}</button></div><div className="permission-row"><div><strong>Brand outward actions</strong><small>{brand.name}</small></div><Badge>{health.brand_paused?'PAUSED':'ACTIVE'}</Badge><button disabled={busy} onClick={()=>run(async()=>{await api('/pause','POST',{brand_id:brand.id,paused:!health.brand_paused});await reloadHealth();refresh()},health.brand_paused?'Brand outward actions resumed':'Brand outward actions paused')}>{health.brand_paused?<Play size={16}/>:<Pause size={16}/>}</button></div></Panel><Panel title="Provider diagnostics"><h3>Ollama</h3><JsonView value={health.ai}/><p className="muted">A failed health check does not block manual authoring or export. Generation remains local to the configured Ollama service.</p><h3>Meta</h3><p>Graph API {String(health.meta_api_version)} · Webhooks {String(health.webhooks)} · Public media {String(health.public_media)}</p><p className="muted">Credentials and authorization are managed for this brand in Settings → Accounts.</p><h3>Storage</h3><p>{String(health.free_gb)} GB free · Encryption {String(health.encryption)}</p></Panel></div>
    </>}</>

  if (page === 'Jobs') return <>
    <div className="toolbar"><p className="muted grow">Durable background queue. Interrupted publishing is held for reconciliation, never blindly retried.</p><button disabled={busy} onClick={()=>run(reloadJobs,'Queue refreshed')}><RefreshCw size={16}/>Refresh</button></div>
    <Status error={jobsError} loading={jobsLoading}/>{!jobsLoading&&!jobs?.length&&<Empty title="No queued work" text="Generation, scheduling, classification, and analytics jobs appear here."/>}
    <div className="operation-list">{jobs?.map(job=><Panel key={job.id}><div className="panel-heading"><div><small className="eyebrow">{label(job.kind)} · JOB #{job.id}</small><h3>{job.target_id?`Target #${job.target_id}`:'Workspace task'}</h3></div><Badge>{job.status}</Badge></div><div className="job-details"><span>Run at {date(job.run_at)}</span><span>{job.attempts} attempts</span><span>{job.error||'No errors reported'}</span></div>{job.status==='UNKNOWN'&&<p className="notice"><ShieldAlert size={16}/> This job needs human inspection. Resolve publication or reply state in its reconciliation workflow.</p>}<div className="button-row">{['PENDING','WAITING'].includes(job.status)&&<button disabled={busy} onClick={()=>run(async()=>{await api(brandPath(brand.id,`/jobs/${job.id}/pause`),'POST');await reloadJobs()},'Job paused')}><Pause size={15}/>Pause</button>}{job.status==='PAUSED'&&<button disabled={busy} onClick={()=>run(async()=>{await api(brandPath(brand.id,`/jobs/${job.id}/resume`),'POST');await reloadJobs()},'Job resumed')}><Play size={15}/>Resume</button>}{!['RUNNING','UNKNOWN','DONE','CANCELLED'].includes(job.status)&&<button disabled={busy} onClick={()=>{if(confirm('Cancel this queued job?'))void run(async()=>{await api(brandPath(brand.id,`/jobs/${job.id}/cancel`),'POST');await reloadJobs()},'Job cancelled')}}>Cancel</button>}</div></Panel>)}</div>
  </>

  if (page === 'Publishing') return <>
    <div className="toolbar"><p className="muted grow">Compare uncertain outcomes with Meta before allowing any retry.</p><button disabled={busy} onClick={()=>run(reloadPublications,'Publishing records refreshed')}><RefreshCw size={16}/>Refresh</button></div>
    <Status error={publicationsError} loading={publicationsLoading}/>{!publicationsLoading&&!publications?.length&&<Empty title="No publication attempts yet" text="Export and publishing attempts are recorded here, including ambiguous outcomes."/>}
    <div className="operation-list">{publications?.map(pub=>{const item=content?.find(entry=>entry.id===pub.content_id);const needsReview=['UNKNOWN','SENDING','CONFIGURATION','RETRY','EXPORTED'].includes(pub.state);return <Panel key={pub.id}><div className="panel-heading"><div><small className="eyebrow">{label(pub.platform)} · PUBLICATION #{pub.id}</small><h3>{item?.topic||`Content #${pub.content_id}`}</h3><small>{item?.status||'Content status unavailable'} · {pub.attempts} attempts</small></div><Badge>{pub.state}</Badge></div>{pub.external_id&&<p>Platform post ID: <code>{pub.external_id}</code></p>}{pub.error&&<p className="error">{pub.error}</p>}{needsReview&&<><p className="notice"><ShieldAlert size={16}/> Check the platform directly. Supply the actual post ID, or confirm absence only after verifying no post was created.</p>{editing===pub.id?<div className="reconcile-form"><Field label="Actual external post ID"><input value={externalId} onChange={event=>setExternalId(event.target.value)} disabled={absent}/></Field><label className="check"><input type="checkbox" checked={absent} onChange={event=>setAbsent(event.target.checked)}/>I verified the platform and confirmed no post was created</label><Field label="Reason and verification notes"><textarea value={reason} onChange={event=>setReason(event.target.value)} rows={3}/></Field><div className="button-row"><button disabled={busy||!reason.trim()||(!externalId.trim()&&!absent)} onClick={()=>run(async()=>{await api(brandPath(brand.id,`/publications/${pub.id}/reconcile`),'POST',{external_id:externalId,confirmed_absent:absent,reason});setEditing(null);setExternalId('');setReason('');setAbsent(false);await reloadPublications()},'Reconciliation recorded')}>Record verified outcome</button><button onClick={()=>setEditing(null)}>Cancel</button></div></div>:<button onClick={()=>{setEditing(pub.id);setExternalId('');setAbsent(false);setReason('')}}><RotateCcw size={16}/>Reconcile outcome</button>}</>}</Panel>})}</div>
  </>

  if (page === 'Backups') return <>
    <div className="toolbar"><p className="muted grow">Backups include the database, brand configuration, renderer font, generated media, and encrypted account tokens. Keep the encryption key separately.</p><button className="primary" disabled={busy} onClick={()=>run(async()=>{await api('/backup','POST');await reloadBackups()},'Backup created')}><Download size={16}/>Create backup</button></div>
    <p className="notice">Keep a separate copy of your encryption key. Restoring invalidates sessions and forces autopilot paused. A safety backup is created before restore.</p><Status error={backupsError} loading={backupsLoading}/>{!backupsLoading&&!backups?.length&&<Empty title="No backups yet" text="Create a backup before your first publishing setup."/>}
    <div className="operation-list">{backups?.map(file=><Panel key={file.name}><div className="panel-heading"><div><h3>{file.name}</h3><small>{new Date(file.created_at*1000).toLocaleString()} · {(file.size/1024/1024).toFixed(2)} MB</small></div><div className="button-row"><a className="button-link" href={apiUrl(`/backups/${encodeURIComponent(file.name)}`)}><Download size={16}/>Download</a><button disabled={busy} onClick={()=>{if(confirm(`Restore ${file.name}? Current data will first be backed up. You will be signed out and autopilot will remain paused.`))void run(async()=>{await api(`/backups/${encodeURIComponent(file.name)}/restore`,'POST');window.dispatchEvent(new Event('dfb:signout'))},'Restore complete; sign in again')}}><RotateCcw size={16}/>Restore</button></div></div></Panel>)}</div>
  </>

  return <>
    <div className="toolbar"><p className="muted grow">Recorded administrative and automated actions for {brand.name}.</p><button disabled={busy} onClick={()=>run(reloadActivity,'Activity refreshed')}><RefreshCw size={16}/>Refresh</button></div>
    <Status error={activityError} loading={activityLoading}/>{!activityLoading&&!activity?.length&&<Empty title="No activity recorded yet" text="Authentication, content, approvals, publishing, and operational changes are recorded here."/>}
    <Panel>{activity?.map(entry=><div className="activity-row" key={entry.id}><span className="activity-dot"/><div className="grow"><strong>{label(entry.action.replaceAll('.',' '))}</strong><small>{entry.actor} · {entry.target||'workspace'}{entry.reason?` · ${entry.reason}`:''}</small></div><Badge>{entry.result}</Badge><time>{date(entry.created_at)}</time></div>)}</Panel>
  </>
}
