import {ArrowUpRight, CheckCheck, CalendarDays, Layers3, MessageCircle, Sparkles, ShieldCheck} from 'lucide-react'
import {useData} from '../hooks/useData'
import {api, brandPath, date, label} from '../services/api'
import {Badge, Empty, Panel, Status, useAction, LinkButton} from '../components/ui'
import type {Brand, Overview as OverviewData} from '../types'

export default function Overview({brand, navigate, refresh}: {brand: Brand; navigate: (page: string, id?: number) => void; refresh: () => void}) {
 const {data, error, loading, reload} = useData<OverviewData>(brandPath(brand.id,'/overview')), {busy,run} = useAction()
 if(!data) return <Status error={error} loading={loading}/>
 const paused = data.paused || brand.paused
 return <><div className="hero"><div><div className="eyebrow">YOUR BRAND, IN GOOD HANDS</div><h2>Make room for<br/><em>the bigger picture.</em></h2><p>A clear view of your content, conversations, and what comes next.</p><button className="primary" onClick={()=>navigate('Create')}><Sparkles size={17}/> Create something useful <ArrowUpRight size={17}/></button></div><div className="autopilot-card"><div className="orb"><ShieldCheck size={36}/></div><Badge>{paused ? 'PAUSED' : 'ACTIVE'}</Badge><h3>{paused ? 'You’re at the controls.' : 'Autopilot is on.'}</h3><p>{paused ? 'Outward automation is paused. Keep creating, reviewing, and planning.' : 'Your brand rules and approval policies guide every action.'}</p><button className="text-button" onClick={()=>navigate('Settings')}>Review automation rules <ArrowUpRight size={15}/></button></div></div>
 <div className="stats">{[{name:'Content coverage',value:`${data.coverage} days`,hint:`${brand.config.schedule.buffer_days}-day target`,icon:CalendarDays},{name:'In the queue',value:data.queue,hint:'Persistent scheduled jobs',icon:Layers3},{name:'Needs your approval',value:data.approvals,hint:'Your judgment matters',icon:CheckCheck},{name:'Open conversations',value:data.community,hint:'Community inbox',icon:MessageCircle}].map(x=><Panel key={x.name}><div className="stat-top">{x.name}<x.icon size={18}/></div><strong className="stat-value">{x.value}</strong><small>{x.hint}</small></Panel>)}</div>
 <div className="columns"><Panel title="Coming up next" action={<LinkButton onClick={()=>navigate('Calendar')}>View calendar</LinkButton>}>
 {data.schedule.length ? data.schedule.slice(0,5).map(c=><button key={c.id} className="list-row clickable" onClick={()=>navigate('Create',c.id)}><div className="date-tile"><CalendarDays size={22}/></div><div className="grow"><strong>{c.topic}</strong><small>{date(c.scheduled_at)} · {label(c.format)}</small></div><Badge>{c.status}</Badge></button>) : <Empty title="A little planning goes a long way" text="Approve your first content item, then give it a place on the calendar." action={<button onClick={()=>navigate('Content')}>Open content library</button>}/>}
 </Panel><Panel title="Your content pipeline"><div className="pipeline">{['DRAFT','REVIEW','APPROVED','SCHEDULED','PUBLISHED'].map(s=><div key={s}><span>{label(s)}</span><div className="bar-track"><div style={{width:`${Math.min(100,(data.counts[s]||0)*10)}%`}}/></div><strong>{data.counts[s]||0}</strong></div>)}</div><div className="panel-note"><Sparkles size={18}/><p>The Content Director balances your pillars and builds from approved knowledge.</p></div><button disabled={busy} onClick={()=>run(async()=>{await api(brandPath(brand.id,'/director'),'POST'); await reload();refresh()},'Content Director queued. Follow progress in System.')}>Maintain content buffer</button></Panel></div>
 <Panel title="A transparent trail" action={<LinkButton onClick={()=>navigate('Activity')}>All activity</LinkButton>}>{data.activity.length ? data.activity.map(a=><div className="activity-row" key={a.id}><span className="activity-dot"/><div className="grow"><strong>{label(a.action.replaceAll('.',' '))}</strong><small>{a.actor} · {a.target || 'workspace'}</small></div><time>{date(a.created_at)}</time></div>) : <Empty title="Your activity will appear here" text="Every important action is recorded."/>}</Panel>
 </>
}
