import {useState} from 'react'
import {useData} from '../hooks/useData'
import {api,brandPath,kinds,label} from '../services/api'
import {Field,Modal,Panel,Status,useAction} from '../components/ui'
import type {Brand,Template} from '../types'
export default function Templates({brand}:{brand:Brand}) {
 const {data,error,loading,reload}=useData<Template[]>(brandPath(brand.id,'/templates')),[editing,setEditing]=useState<Template|null>(null),{busy,run}=useAction()
 return <><div className="toolbar"><p className="muted grow">Deterministic 1080 × 1350 layouts. Typography scales to fit; overflow fails visibly.</p><button onClick={()=>setEditing({id:0,name:'New template',kind:'tip',config:brand.config.visual,enabled:true})}>Add template</button></div><Status error={error} loading={loading}/><div className="template-grid">{data?.map(t=><Panel key={t.id}><div className="template-sample" style={{background:t.config.background,color:t.config.foreground}}><small>{t.config.mark}</small><h3>{label(t.kind)}</h3><div style={{background:t.config.accent}}/><p>{t.kind==='steps'?'01  A clear first step\n02  One thing at a time':t.kind==='checklist'?'A little order.\nA lot more breathing room.':'Practical notes for everyday life.'}</p><small>LAYOUT PREVIEW</small></div><div className="panel-heading"><h3>{t.name}</h3><small>{t.enabled?'Enabled':'Disabled'}</small></div><button onClick={()=>setEditing(t)}>Edit identity</button></Panel>)}</div>{editing&&<Modal title="Edit template" close={()=>setEditing(null)}><Field label="Name"><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="Layout"><select value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value})}>{kinds.map(k=><option key={k} value={k}>{label(k)}</option>)}</select></Field>{(['background','foreground','accent','muted'] as const).map(k=><Field key={k} label={label(k)}><input type="color" value={editing.config[k]} onChange={e=>setEditing({...editing,config:{...editing.config,[k]:e.target.value}})}/></Field>)}<Field label="Brand mark"><input value={editing.config.mark} onChange={e=>setEditing({...editing,config:{...editing.config,mark:e.target.value}})}/></Field><label className="check"><input type="checkbox" checked={editing.enabled} onChange={e=>setEditing({...editing,enabled:e.target.checked})}/>Enabled</label><button className="primary" disabled={busy} onClick={()=>run(async()=>{await api(brandPath(brand.id,editing.id?`/templates/${editing.id}`:'/templates'),editing.id?'PUT':'POST',{name:editing.name,kind:editing.kind,config:editing.config,enabled:editing.enabled});setEditing(null);await reload()},'Template saved')}>Save template</button></Modal>}</>
}
